# Generated by Django 2.2 on 2019-07-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20190630_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.AddField(
            model_name='task',
            name='priority1',
            field=models.CharField(choices=[('LW', 'Low'), ('MD', 'Medium'), ('HG', 'High')], default='LW', max_length=2),
        ),
    ]
