# Generated by Django 2.2 on 2019-07-02 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20190702_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='priority1',
            new_name='priority',
        ),
    ]
